language: php
php:
- 7.2
- 7.3
cache:
  directories:
  - vendor
notifications:
  email: false
script: echo 'Orgmanager Running'
deploy:
  provider: heroku
  api_key:
    secure: QdpGd+RXf23CHghA5KpynjwwM+q2fFVaFQ6YuCg2Ih9C53kxi60Yq93DChzUvy7JXGdlP1brGslp1vGwJvpnsGdtazwFvVSzFrpEJk6ZaSQUdocWtokmfyjJHPh3CkYbejbyvKkO4xGykUv3U36rN+V4Nw4u6zXdVqqNsz701zwdcxqhuq6l5yk2DUWAodqcgNDWQ7hJasJ8l566Sy1cQjdKNbYBG4o1E1ejRx/19T2B6UZukemdBfOoJ7pphqQOKTJ7rAG6DENwh3o6XHmdpyBtGJIhNlVfLMNUYQJcKsxUWm27hQ78cz78DfOzAe+4adek8d3ViFesr+9Pz5dAfXqraJ+yKOu3I9qaqnp6u7eEmwocYf9ujNk9hy8lvX0zCAAWlo7iX+JtlEAfb3KJynj105b0l4BWIhleuM1hkuanqz4W8wd62tmu/IZw76xXxkLh9/tZsphH1yv2P3lbfI67/eCAquN4+RsBgclRL3Hsqa0t+VmgwWFxULk3prwpRdDkdHtjRXmZKruP0XFnkI/flx4Lzunh3aMY2nUhbSGgDYkJa2cwj/BCx7uXLCtkmpx8E/cf93OuTC3kDDSfu6fmuqLxCSfaBlfcEn+aEHcorgkv+Cb3D994xsbawP9y55kbl3HRgDdWoJIGZsfLNDO08Ehv6zK6nt4/PZQCwoQ=
