language: php
php:
- 7.2
- 7.3
cache:
  directories:
  - vendor
notifications:
  email: false
script: echo 'Orgmanager Running'
deploy:
  provider: heroku
  api_key:
    secure: E58p7uaeHE9xb4SGyVO1iFjvVyLs03RjYIhMX8k38nrWruKebgut1656Ln7rbBcbIVnDejmWv6FghAc5fPtpN9yDdKfUeMuxkyuJuzhcvpOznzqnFUY94B3CAA0KP+2MNSM+aNlGgPCLbJHENslddJ+vVYGUg/J9HMY1oOSYj8dxACuWFbL0lkTeRw1CooUwUbrhOdQWp+fPa/BBFZhEAPiX+D7czuey+YhWdOEWjSqSJGw64Dh3PgvqGOg6MpLMwy+s2uWIbwVRWzTpwMkzTNHOyL4ZAdopT5uF69QtV3AKHsTI9beEA/B5gA3uJObHsYoB9kl88AM+S0Xk8XZQ9m2G1+x+0aABhkp2ngdqtB0eiDbBFAA+xuaWtgQmBXpxl+1u48jxPbIDFnWbcnJlwnkHlC6EwHzw33kiZ/Qkkiq+8iGCBhalB610USDDJ2KUgJ8b0VJOQwjKGLpurbzd8ktiJRfpTI2WdYs0+gJMEslNbGVbsyCFzNLCVEsx5/jtaJmthpU8n1ak+laltGpnhB/skLS1u3hve0lKE+z9ENugzl3TSi3Q//FDjgb6as6YBV8XZNgLIVsjmkn9AKgM5sFqbb4sVahyYedbgIlglz/d2z1kkkcX38kc8w67/VwbwDXCXS9dvnw6HyITMljN+RmwhUrphsFsNGYAkFRfkVk=
