language: php
php:
- 7.2
- 7.3
cache:
  directories:
  - vendor
notifications:
  email: false
script: echo 'Orgmanager Running'
deploy:
  provider: heroku
  api_key:
    secure: Td+9CAgyw+NaKGYaZf9AiCSgyI3EU+wm7ASjdu7efzrCtWPqd9Qg/eUHvbhtgCWckkLYWDo46gryds4u8WzRu2GV0kIFRYG3XYkyBIuRibtntVV/21ygriYrqk8dr4Jo/WcXxPey/cN/uTCFfoa7NaLQR5YdVO3XTK0Oz2wF9h9Np9oDCnEJ6w2SnQCasFdCwKWTZGZ7St3AMS8B+KC75bxqFckGULla/Nua2psF6J71N8gQandJSbbpfdcqAHTDvbCu0PPcO8vG5JLVhz4Bzf+rkE+3pBdfKcJK1bZ5AdFBmw8J0t65Z7ZsHlVEEZoxLE51kqHZd4X9NNT8xY7OPKX5GxW3zRBLr4NfpEVVL5nQq1J4v/4Rpmmrya9PkWUNnUIzeuPB5wjPf685JuC//sGcuzKz3ZhrMJWBnOivSF/wFhgyhYXJImypMo0yJiPtlaqghfNxmU0i0/xoMezyleyEJi3YPob4lMGm2LDkVj8ttIRPD3IzTgdUsR7yNBRKy9iQp6/1zLqBUeFRfPJOMUpoMSgALaQ5p2c3DurmEMq7mM2IJ4gRHifA+z4XHZXDXsqje3O26PjEJ8l6Jk8ymPbO3Cdx2N6Q8Y4pj/gPoP9Wwxxoq+zkVGEs9NXxNdYquJOpTPPLwfc6wW/1tTlOWvcme0XCevHOFp7hwTQQ4MQ=
