language: php
php:
- 7.2
- 7.3
cache:
  directories:
  - vendor
notifications:
  email: false
script: echo 'Orgmanager Running'
deploy:
  provider: heroku
  api_key:
    secure: cmhwXjicf6rv3/pemrv8mKE8Q3bLOBcxQjJw03L4fIqjWKwD6kDfHfauudX4/qX8LF+fWS5cXoYe/H8L5pkb0hSENidkNnB/cLrmGt846fQRE/haEQodoRy7v5Yh6RUU22z0aD1Vm9O/pDrA/HmNuNjjO9ZUwKpfvqy9CV+83JcSAmV5RUjIv7KYaRPrlry997588Ox7URfIy68V+dhHdxfPiedHvAtDoYhXEouyEln7unJKRhr/8nES6IryuXk52R656itVfJAmKKH1mPtwXvHIhMgHRbEpzWIO9/VclTBlHl7DaJ7ScuiX5yTAX1MYKE1VO0inG8lScC97YQtFsFV1X5KE4/XqAtGdyrrREHcSzg++4RVYxc5oUtgfYR5LXEQp3D0J/fJwDSHgYNvw3gLdaCJ+oW6qyEppx8EJapZl5Kq2sKWY2mLwj/n3Ui5v3rvijiz98lnZKVtiHIFYVEqYPkXxB8tUYWgWMqQd7TNKFyv6YXo3ubc3Cnr3PGumCXXV4bgfWPx4Z+QeNlIbeWvl0G+0hs0JMqSCc4adbzMryH2U8Ir8vMyB7lO+713OTDZAvouxnQ/zaXSoq2NLuWWwMWwBPJuSLf8LUahYRmTLp99ndMGAjnqvtazgKbShVkr//uSTHxQMJkhew0duOa+IVgzbg+1xY4DafAv1j1Q=
  app: orgmanager
  repo: fossasia/orgmanager
