language: php
php:
- 7.2
- 7.3
dist: trusty
sudo: false
cache:
  directories:
  - vendor
notifications:
  email: false
addons:
  ssh_known_hosts:
  - "<your-host.tld>:<portnumber>"
before_install:
- eval "$(ssh-agent -s)"
- cp .travis/id_rsa ~/.ssh/deploy_rsa
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa
- openssl aes-256-cbc -K $encrypted_953e1899685a_key -iv $encrypted_953e1899685a_iv
  -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
- eval "$(ssh-agent -s)"
- cp .travis/id_rsa ~/.ssh/deploy_rsa
- chmod 600 ~/.ssh/deploy_rsa
- ssh-add ~/.ssh/deploy_rsa
script: echo 'Orgmanager Running'
deploy:
- provider: heroku
  api_key:
    secure: tMmSyVmT+LUwejU/UxVLBmHh8Mad9lGMKVt/gWzZK407CIru2Thn8vqj/tiN6WzeSTP1RoU7zqQiGE8740xY4rUweX9vHw33NjJSAFjHzcloeFu3r1I6Ar9Z3LEaquELsBzilWXxAPYgif2dt0WpI5jgPcJVm4/czpsINrU/wt7DMNzJuNJqMLPkIUdKTI7v9L/qP7S77KtAoUMnU7b0s16ZoOCWP7mCvhd2MgHoAxRkiYLOtFf5zjPvYLgLrAnftpFpOrEbZVeUlBuJOmCR0jR9RfelhU8sU2qEgZ79PZjmYLqfybcBt1eRdyvn1AEnTD8fp1zKY5bTBe6aL0aQHlbAreiI3+xTTT9vNKWzr1vmssnsglmKtCcoi6BP1MVmht+FCaG4ZSn12nt8tpfDnJcFtlSErTxZ8XJ6fDvCKs6UkGtlDP0dFccsN9Mr6tKYQlJyrRjK1YmmKcxylQ0LIBEEVYLt19ac7s1ogJ11QlVe2DbMAiJIw7PjzBz0p77pkkNS+8ihc1s+HoFlr+QUsmTm43SNR0KnFxXcO2azSW7VmS154gPviZmzeJRdvmp5O7mZ69tbGrdY0gk3GvaymjPeZjqNRL0ALvDN+9zc9kTO3Wh/qNIYDylY0hHk87XzfraviNt7DZ1agH92BDwsrcGJhBBxFNIMxu/ut6S4V9k=
  app: orgmanager
  repo: fossasia/orgmanager
- provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"
  on:
    branch: master
